## AWS Config resources for region: ap-southeast-2 - generated by /src/template_gen.sh
provider "aws" {
  region = "ap-southeast-2"
  alias  = "ap-southeast-2"
}

resource "aws_config_aggregate_authorization" "ap_southeast_2_config_auth" {
  provider   = aws.ap-southeast-2
  account_id = var.audit_account_id == "self" ? data.aws_caller_identity.current.account_id : var.audit_account_id
  region     = "ap-southeast-2"
}

resource "aws_config_delivery_channel" "ap_southeast_2_to_central_audit_bucket" {
  provider       = aws.ap-southeast-2
  name           = "audit_account_config_bucket"
  s3_bucket_name = "${var.customer_prefix}-aws-config-delivery-bucket"
  depends_on     = [aws_config_configuration_recorder.ap_southeast_2_account_recorder]
}

resource "aws_config_configuration_recorder" "ap_southeast_2_account_recorder" {
  provider = aws.ap-southeast-2
  name     = "central_audit_account_recorder"
  role_arn = aws_iam_service_linked_role.config.arn
  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_config_configuration_recorder_status" "ap_southeast_2_enable_account_recording" {
  provider   = aws.ap-southeast-2
  name       = aws_config_configuration_recorder.ap_southeast_2_account_recorder.name
  is_enabled = true
  depends_on = [aws_config_delivery_channel.ap_southeast_2_to_central_audit_bucket]
}

