## AWS Config resources for region: us-west-2 - generated by /src/template_gen.sh
provider "aws" {
  region = "us-west-2"
  alias  = "us-west-2"
}

resource "aws_config_aggregate_authorization" "us_west_2_config_auth" {
  provider   = aws.us-west-2
  account_id = var.audit_account_id == "self" ? data.aws_caller_identity.current.account_id : var.audit_account_id
  region     = "us-west-2"
}

resource "aws_config_delivery_channel" "us_west_2_to_central_audit_bucket" {
  provider       = aws.us-west-2
  name           = "audit_account_config_bucket"
  s3_bucket_name = "${var.customer_prefix}-aws-config-delivery-bucket"
  depends_on     = [aws_config_configuration_recorder.us_west_2_account_recorder]
}

resource "aws_config_configuration_recorder" "us_west_2_account_recorder" {
  provider = aws.us-west-2
  name     = "central_audit_account_recorder"
  role_arn = aws_iam_service_linked_role.config.arn
  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_config_configuration_recorder_status" "us_west_2_enable_account_recording" {
  provider   = aws.us-west-2
  name       = aws_config_configuration_recorder.us_west_2_account_recorder.name
  is_enabled = true
  depends_on = [aws_config_delivery_channel.us_west_2_to_central_audit_bucket]
}

