#!/bin/bash
# Usage:
# $ for i in $(aws ec2 describe-regions --output text | awk '{print $4}'); do rm -rf config_$i.tf && ./src/template_gen.sh $i > config_$i.tf; done

underscored=$(echo "$1" |  sed -r 's/-+/_/g')

cat <<EOF
## AWS Config resources for region: $1 - generated by /src/template_gen.sh
provider "aws" {
  region = "$1"
  alias  = "$1"
}

resource "aws_config_aggregate_authorization" "${underscored}_config_auth" {
  provider   = aws.$1
  account_id = var.audit_account_id == "self" ? data.aws_caller_identity.current.account_id : var.audit_account_id
  region     = "$1"
}

resource "aws_config_delivery_channel" "${underscored}_to_central_audit_bucket" {
  provider       = aws.$1
  name           = "audit_account_config_bucket"
  s3_bucket_name = "\${var.customer_prefix}-aws-config-delivery-bucket"
  depends_on     = [aws_config_configuration_recorder.${underscored}_account_recorder]
}

resource "aws_config_configuration_recorder" "${underscored}_account_recorder" {
  provider = aws.$1
  name     = "central_audit_account_recorder"
  role_arn = aws_iam_service_linked_role.config.arn
  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_config_configuration_recorder_status" "${underscored}_enable_account_recording" {
  provider   = aws.$1
  name       = aws_config_configuration_recorder.${underscored}_account_recorder.name
  is_enabled = true
  depends_on = [aws_config_delivery_channel.${underscored}_to_central_audit_bucket]
}

EOF
